Feature/225 display dvh lvh
pytrip/pytripgui pull request #342
Opened 2020-11-09 02:26 UTC by ljelen

work in progress

2020-11-09 02:27 UTC, ljelen commented
Preview picture 

![image](https://user-images.githubusercontent.com/47323191/98493711-69e59300-223b-11eb-9ac1-c4080cbe8979.png)

2020-11-09 11:42 UTC, grzanka commented on pytripgui/view/chart_widget.py
> +        for x, y in let_chart:
why not ue `zip`:

```
for x,y in zip(xserie,yserie):
#    dos th with x,y`
```

2020-11-12 07:57 UTC, grzanka requested changes
Few minor comments

2020-11-12 07:57 UTC, grzanka commented on pytripgui/app_logic/chars.py
> +            for organ_name in histogram:
improve looping technique:

```
for name, value in some_dict.items():
    widget.add...(value.x, name)
```

2020-11-12 07:57 UTC, grzanka commented on pytripgui/view/chart_widget.py
> +        for x, y in zip(x, y):
It is bad idea to use same variable names for iteration as for arguments in `zip` function.
Better would be:
```
for xlist, ylist in zip(x,y):
    series.append(xlist, ylist)
```

2020-11-12 12:40 UTC, grzanka approved these changes
Looks OK now

2020-11-12 12:40 UTC, merged