target as list with radio-buttons
pytrip/pytripgui pull request #347
Opened 2020-11-23 12:43 UTC by ljelen

closes #346

2020-11-23 12:49 UTC, grzanka commented
User is still permitted to make no selection of Target ROI and Click OK. Afterwards user can create a field, click execute and get ugly error:
```
(pytripgui_dicom_target) grzanka@grzanka-VirtualBox:~$ pytripgui 
/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/viewcanvas_vc/viewcanvas_view.py:306: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  cax = self.axes.figure.add_axes([0.1, 0.1, 0.03, 0.8])
WARNING:pytripgui.plan_vc.plan_view:Given kernel wasn't found on the list
6
Traceback (most recent call last):
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/main_window_qt_vc/main_window_cont.py", line 68, in on_execute_selected_plan
    sim_results = self.app_callback.execute_plan(
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/app_logic/app_callbacks.py", line 84, in execute_plan
    item.data = self.executor.execute(patient.data, plan.data)
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/plan_executor/executor.py", line 35, in execute
    te.execute(plan)
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/execute.py", line 139, in execute
    plan.save_exec(plan._exec_path)  # add the .exec as well
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 263, in save_exec
    self.make_exec()
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 336, in make_exec
    output.extend(self._make_exec_input())  # input data, CT and VDX
  File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 414, in _make_exec_input
    _name = self.voi_target.name.replace(" ", "_")
AttributeError: 'NoneType' object has no attribute 'name'
Aborted (core dumped)
```

2020-11-23 12:51 UTC, grzanka commented
@ljelen can you also vertically align list of target ROIs to list of OARs ?
![image](https://user-images.githubusercontent.com/7374733/99964023-f3947500-2d92-11eb-9eab-b204491751fa.png)

2020-11-23 13:16 UTC, grzanka requested changes
Fix it

2020-11-23 13:16 UTC, grzanka commented on pytripgui/plan_vc/plan_view.py
> +        print(item_count)
remove debugging printout

2020-11-23 13:16 UTC, grzanka commented on pytripgui/plan_vc/plan_view.py
> +        for i in range(item_count):
Are you force to use iteration with index `i` ? I suspect there should be some iterator available in `self.ui.targetROI_listWidget`

2020-11-25 04:39 UTC, ljelen commented
> User is still permitted to make no selection of Target ROI and Click OK. Afterwards user can create a field, click execute and get ugly error:
> 
> ```
> (pytripgui_dicom_target) grzanka@grzanka-VirtualBox:~$ pytripgui 
> /home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/viewcanvas_vc/viewcanvas_view.py:306: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
>   cax = self.axes.figure.add_axes([0.1, 0.1, 0.03, 0.8])
> WARNING:pytripgui.plan_vc.plan_view:Given kernel wasn't found on the list
> 6
> Traceback (most recent call last):
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/main_window_qt_vc/main_window_cont.py", line 68, in on_execute_selected_plan
>     sim_results = self.app_callback.execute_plan(
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/app_logic/app_callbacks.py", line 84, in execute_plan
>     item.data = self.executor.execute(patient.data, plan.data)
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytripgui/plan_executor/executor.py", line 35, in execute
>     te.execute(plan)
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/execute.py", line 139, in execute
>     plan.save_exec(plan._exec_path)  # add the .exec as well
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 263, in save_exec
>     self.make_exec()
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 336, in make_exec
>     output.extend(self._make_exec_input())  # input data, CT and VDX
>   File "/home/grzanka/.conda/envs/pytripgui_dicom_target/lib/python3.8/site-packages/pytrip/tripexecuter/plan.py", line 414, in _make_exec_input
>     _name = self.voi_target.name.replace(" ", "_")
> AttributeError: 'NoneType' object has no attribute 'name'
> Aborted (core dumped)
> ```

![image](https://user-images.githubusercontent.com/47323191/100183927-81ca4180-2ee0-11eb-8b1f-3b085aa1b54b.png)

2020-11-26 10:59 UTC, grzanka requested changes

2020-11-26 10:59 UTC, grzanka commented on pytripgui/messages.py
> +        "Please select at least one TargetROI in 'Target' tab"]
This text doesn't make sense, as by design user can specify exactly one TargetROI. Why then adding `at least one` ?

2020-11-26 11:30 UTC, grzanka approved these changes

2020-11-26 11:46 UTC, merged