Executable on older Windows
pytrip/pytripgui pull request #469
Opened 2021-08-29 21:48 UTC by michal367

Older Windows e.g. Windows 7 needs api-ms-win-* and ucrtbase dlls that were missing.

2021-08-31 07:39 UTC, grzanka commented on appveyor.yml
> +image: Visual Studio 2019
please explain in comment why this particular VS is needed

2021-09-02 19:48 UTC, grzanka requested changes

2021-09-02 19:48 UTC, grzanka commented on appveyor.yml
> +  - set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%star
do I see correctly `star` appended ?

2021-09-02 19:50 UTC, rozchlastywacz commented on appveyor.yml
> +  - set PATH="C:\Program Files (x86)\Inno Setup 6";%PATH%star
So do I :)

2021-09-02 19:50 UTC, grzanka approved these changes
ok

2021-09-02 19:57 UTC, merged