fixing contributor list
pytrip/pytripgui pull request #495
Opened 2021-09-03 19:41 UTC by grzanka

Fixes #492

2021-09-03 20:16 UTC, rozchlastywacz requested changes

2021-09-03 20:16 UTC, rozchlastywacz commented on pytripgui/messages.py
> +    Arkadiusz Cwikła
if you are using polish letters, please use them in mine name as well :)

2021-09-03 20:16 UTC, rozchlastywacz commented on setup.py
> +    author='Niels Bassler at el.',
did you mean `et al`?

2021-09-03 20:17 UTC, rozchlastywacz commented on pytripgui/messages.py
> +    Michal Krawczyk
and also in his name ;)

2021-09-07 10:52 UTC, michal367 commented on setup.py
> +    author='Niels Bassler et el.',
et al.

2021-09-07 11:19 UTC, grzanka commented on setup.py
> +    author='Niels Bassler et el.',
done

2021-09-07 11:31 UTC, michal367 approved these changes

2021-09-07 11:47 UTC, rozchlastywacz approved these changes
Nice

2021-09-07 11:48 UTC, merged