Missing docs in set_patient
pytrip/pytripgui pull request #496
Opened 2021-09-03 21:28 UTC by rozchlastywacz

closes #479 
- #479

2021-09-07 11:50 UTC, grzanka requested changes

2021-09-18 22:20 UTC, rozchlastywacz commented on pytripgui/canvas_vc/canvas_controller.py
> +        Sets patient data (CTX and VDX) to be displayed on canvas
Done

2021-09-18 22:20 UTC, rozchlastywacz commented on pytripgui/canvas_vc/canvas_controller.py
> +            and restores GUI state (slider height, its position in each plane and ticked VOIs) if it exists.
Done

2021-09-19 20:15 UTC, grzanka approved these changes
Looks good

2021-09-19 20:15 UTC, merged